### ISSUE TITLE
User actions that trigger programmatic publishing does not create a snapshot

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-versioned-snapshots#42]
This is a critical issue for any site that publishes content via programmatic calls to e.g. `publishRecursive`, e.g. as the result of an event or workflow approval.

It is most notable for sites that make use of Advanced Workflow ([`symbiote/silverstripe-advancedworkflow`](https://github.com/symbiote/silverstripe-advancedworkflow)).

E.g. using the standard 2 step review & approve workflow, the save event is recorded as a version in a snapshot, but the approve and subsequent automatic publish is not.

## Recreation

However this is most _easily_ demonstrated simply with a fresh install and no extra actions:

- `composer create-project silverstripe/recipe-cms historytest`
- `composer require silverstripe/versioned-snapshot-admin`
- `dev/build`
- visit `admin/pages/history/show/2` as the Default Admin

![image](https://user-images.githubusercontent.com/778003/114642765-95a80000-9d28-11eb-9fb8-a37281132ee1.png)

![image](https://user-images.githubusercontent.com/778003/114645844-495fbe80-9d2e-11eb-81e7-55168549eba3.png)

**Comment by unclecheese** [comment]
This is a known tradeoff for the event-based approach we chose for snapshots a while back. Creating snapshots on database write was fraught with issues that affected not only performance, but also created a confusing history. By tying snapshots to user actions, we're able to create a much more verbose description of what happened, rather than a low-level interpretation of one or many database mutations.

But the cost of that is the opposite problem -- you can't capture everything. So we just need to plug these holes as we find them. Workflow appears to be one of them.

To fix:

* `PublishItemWorkflowAction` and `WorkflowPublishTargetJob` invoke new `->extends()` hooks after publish
* Create an extension in snapshots that handles this extension point, and fires an event
* Create an event handler that creates a snapshot publish record (see PublishHandler in snapshots)
* Add event handler to dispatcher (see existing configurations)

All config related to this should be in a `moduleexists: symbiote/silverstripe-advancedworkflow` block.

Estimate: one dev day

**Comment by unclecheese** [comment]
Ready for review: https://github.com/silverstripe/silverstripe-versioned-snapshots/pull/43

**Comment by NightJar** [comment]
Due to the clarification that programmatic publishing is not intended to be captured, but rather user driven events that might cause a publish, I've updated the title.

The case with Advanced Workflow is now fixed as it captures the publish event triggered by an "approve" in a standard "review & approve" workflow.

![image](https://user-images.githubusercontent.com/778003/116946635-c39cb680-acce-11eb-992a-c2c1a998b9c8.png)

Using standard workflow:
![image](https://user-images.githubusercontent.com/778003/116946761-19715e80-accf-11eb-84b5-201d6470e2b2.png)
_User action is circled, the arrow points to the programmatic publish step_
